cameras:
  - RTSP:
      id: Cam02
      ipAddress: 192.168.1.202
  - RTSP:
      id: Cam03
      ipAddress: 192.168.1.203
  - RTSP:
      id: Cam04
      ipAddress: 192.168.1.204
  - RTSP:
      id: Cam05
      ipAddress: 192.168.1.205
  - RTSP:
      id: Cam06
      ipAddress: 192.168.1.206
  - RTSP:
      id: Cam07
      ipAddress: 192.168.1.207
  - RTSP:
      id: Cam08
      ipAddress: 192.168.1.208
  - RTSP:
      id: Cam09
      ipAddress: 192.168.1.209

logging:
  level: debug

output:
  rootFolder: '/home/tim/projects/personal/nvrrecorder/video'
  retention: P5D
